### ISSUE TITLE
Unable to parse / missing tag value

### ISSUE THREAD

**Issue by pjcortes** [jorgedlcruz/veeam-availability-console-grafana#2]
Hello Jorge,

When I execute the script, I receive the following errors:

`HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: 08acbe87-7023-11e9-8325-000c294005bd
X-Influxdb-Build: OSS
X-Influxdb-Error: unable to parse 'veeam_vac_vcclicense,edition=,status=,type=,contactPerson=,backupServerName=,companyName= licenseExpirationDate=1557100800,supportExpirationDate=1557100800,licensedCloudConnectBackups=,usedCloudConnectBackups=,licensedCloudConnectReplicas=,usedCloudConnectReplicas=,licensedCloudConnectServers=,usedCloudConnectServers=,licensedCloudConnectWorkstations=,usedCloudConnectWorkstations=': missing tag value
X-Influxdb-Version: 1.7.6
X-Request-Id: 08acbe87-7023-11e9-8325-000c294005bd
Date: Mon, 06 May 2019 17:18:58 GMT
Content-Length: 433

{"error":"unable to parse 'veeam_vac_vcclicense,edition=,status=,type=,contactPerson=,backupServerName=,companyName= licenseExpirationDate=1557100800,supportExpirationDate=1557100800,licensedCloudConnectBackups=,usedCloudConnectBackups=,licensedCloudConnectReplicas=,usedCloudConnectReplicas=,licensedCloudConnectServers=,usedCloudConnectServers=,licensedCloudConnectWorkstations=,usedCloudConnectWorkstations=': missing tag value"}

HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: 08bc0cfa-7023-11e9-8326-000c294005bd
X-Influxdb-Build: OSS
X-Influxdb-Error: unable to parse 'veeam_vac_vaclicense,productName=,licensedTo=,licenseType=,licensesCount=,licensesUsedCount=,supportID= licenseExpirationDate=1557100800,supportExpirationDate=1557100800,licensevmCount=,licenseworkstationCount=,licenseserverCount=,licensecloudWorkstationCount=,licensecloudServerCount=,licensecloudconnectBackupVmCount=,cloudconnectBackupWorkstationCount=,cloudconnectBackupServerCount=,cloudconnectReplicationVmCount=': missing tag value
X-Influxdb-Version: 1.7.6
X-Request-Id: 08bc0cfa-7023-11e9-8326-000c294005bd
Date: Mon, 06 May 2019 17:18:58 GMT
Content-Length: 468

{"error":"unable to parse 'veeam_vac_vaclicense,productName=,licensedTo=,licenseType=,licensesCount=,licensesUsedCount=,supportID= licenseExpirationDate=1557100800,supportExpirationDate=1557100800,licensevmCount=,licenseworkstationCount=,licenseserverCount=,licensecloudWorkstationCount=,licensecloudServerCount=,licensecloudconnectBackupVmCount=,cloudconnectBackupWorkstationCount=,cloudconnectBackupServerCount=,cloudconnectReplicationVmCount=': missing tag value"}
`
Thank you
Paul

**Comment by pjcortes** [comment]
I found the issue, it was user error. Closing.

**Comment by Raynok** [comment]
@pjcortes @jorgedlcruz 

What was the issue and what did you do to resolve it. I'm stuck with the same output and
believe we using the latest VAC version.

Cheers

**Comment by Raynok** [comment]
Hi @pjcortes @jorgedlcruz 

Please help, I'm still not able to resolve.

**Comment by Raynok** [comment]
Hi @pjcortes @jorgedlcruz

Please help, I'm still not able to resolve.

**Comment by Raynok** [comment]
Hi @pjcortes @jorgedlcruz

Please help, I'm still not able to resolve.
